// Package relaytoken implements Layer 3 relay access verification.
// relay_token = base64url(HMAC-SHA256(relaySecret, userID+":"+expiryUnix)) + "." + expiryUnix
// Generated by dudenest-hub (GET /user/relays) using relay_secret from CRDB.
// Verified by relay middleware using relay_secret from env (RELAY_SECRET).
// This binds token to a specific user AND relay — cannot be reused across relays or users.
package relaytoken

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"strconv"
	"strings"
	"time"
)

// Verify returns true if token is valid, unexpired, and was issued for (relaySecret, userID).
// Returns false immediately if any parameter is empty or token is malformed.
func Verify(token, relaySecret, userID string) bool {
	if token == "" || relaySecret == "" || userID == "" { return false }
	parts := strings.SplitN(token, ".", 2)
	if len(parts) != 2 { return false }
	expiry, err := strconv.ParseInt(parts[1], 10, 64)
	if err != nil || time.Now().Unix() > expiry { return false }
	mac := hmac.New(sha256.New, []byte(relaySecret))
	mac.Write([]byte(userID + ":" + parts[1]))
	expected := base64.RawURLEncoding.EncodeToString(mac.Sum(nil))
	return hmac.Equal([]byte(parts[0]), []byte(expected)) // constant-time comparison
}
